### ISSUE TITLE
Enable user to deploy to ocp4 cluster of PSI

### ISSUE THREAD

**Issue by harshad16** [AICoE/aicoe-cd#128]
**Is your feature request related to a problem? Please describe.**
currently, the ocp4 cluster from psi is not available in list of clusters for deployments.
It would be very helpful for the users of the ocp4 clusters.

**Describe the solution you'd like**
enable cluster ocp4 in the list of cluster aicoe-cd manages.

**Describe alternatives you've considered**
deploy it with kustomize manually 

**Additional context**
![cluster_missing](https://user-images.githubusercontent.com/14028058/94557067-afe22b00-027b-11eb-859c-293f0f76287e.png)

**Comment by anishasthana** [comment]
Hey @harshad16 . @HumairAK will be migrating ArgoCD to the new OpenShift4 cluster soon, so I think this work could fall into that. Is adding ocp4 a major blocker for you?

**Comment by HumairAK** [comment]
Just saw this, it should have been available, i'll take a look .

**Comment by HumairAK** [comment]
should be there now !

**Comment by harshad16** [comment]
Thanks for the quick fix. :rocket:
