### ISSUE TITLE
enable user to deploy to kaizen cluster of MOC

### ISSUE THREAD

**Issue by harshad16** [AICoE/aicoe-cd#130]
**Is your feature request related to a problem? Please describe.**
currently, the kaizen cluster from moc is not available in the list of clusters for deployments.
It would be very helpful for the users of the moc-kaizen clusters.

**Describe the solution you'd like**
enable cluster moc kaizen in the list of cluster aicoe-cd manages.

**Describe alternatives you've considered**
deploy it with kustomize manually 

**Additional context**
https://k-openshift.osh.massopen.cloud:8443

**Comment by HumairAK** [comment]
Hrmm I don't have access to this cluster, whom do I contact to get access?

**Comment by goern** [comment]
what is the status here?

**Comment by HumairAK** [comment]
my question is the same, to add the cluster we need the following: 
- a service account named `argocd-manager` on this cluster and the contents of `oc sa get-token argocd-manager -n <namespace>` where `<namespace>` is where this SA lives. 
- create a cluster spec for this cluster like the ones [here](https://github.com/AICoE/aicoe-cd/tree/master/manifests/overlays/prod/secrets/clusters). 
More information on how to do all this can be found [here](https://aicoe.github.io/aicoe-cd/admin/add_new_cluster_spec/)

**Comment by harshad16** [comment]
Thanks, @HumairAK for all the details.
sorry, didn't see your preview of the message.
if you want access to the cluster for any other work, you can create a ticket to get access from here: https://osticket.massopen.cloud/index.php

I will open a pull request to get this resolve, thanks as we can create all of the required files I suppose.

**Comment by HumairAK** [comment]
cluster has been added, please test out an app deployment and let us know if there are issues

**Comment by harshad16** [comment]
Thanks for all the help.
