### ISSUE TITLE
sync issue is happening for ocp4 cluster.

### ISSUE THREAD

**Issue by harshad16** [AICoE/aicoe-cd#134]
**Describe the bug**
we have moved the application aicoe-ci to be deployed to ocp4 cluster via argocd.
https://github.com/AICoE/aicoe-cd/blob/master/manifests/overlays/prod/applications/thoth-station/bots/aicoe-ci.yaml

`aicoe-argocd-manager` rolebinding is already created in ocp4 namespace where the application is to sync.

however it is facing issue: 
![aicoe-argocd](https://user-images.githubusercontent.com/14028058/94801971-7c7ed800-0404-11eb-8699-50697e90b72b.png)

**To Reproduce**
1. create an application to be deployed on ocp4 cluster.
2. Click on 'argocd ui'
3. Scroll down to 'Errors' on the application

**Expected behavior**
sync with ease on ocp4 cluster.

**Additional context**
we can remove this from kustomize, until the ocp4 sync issues are fixed.
https://github.com/AICoE/aicoe-cd/blob/2c323e926d28f9e540d2e0fd8d5a63ff849c19a5/manifests/overlays/prod/applications/thoth-station/kustomization.yaml#L4
I have manually deployed the application so there is no urgency.

**Comment by HumairAK** [comment]
@harshad16 can you create the argocd-manage rolebindings in all the thoth namespaces listed here: https://github.com/AICoE/aicoe-cd/blob/master/manifests/overlays/prod/secrets/clusters/api.ocp4.prod.psi.redhat.com.enc.yaml#L13

**Comment by harshad16** [comment]
@HumairAK  i have added the rolebinding for all thoth projects.
Dont have access for aicoe-argocd.

**Comment by HumairAK** [comment]
Not seeing any errors now for this cluster, try again and let us know if it works! :)

**Comment by harshad16** [comment]
This is fixed and working well.
Thanks @HumairAK
