### ISSUE TITLE
argo-cd is not syncing from vcs due to credential issues

### ISSUE THREAD

**Issue by harshad16** [AICoE/aicoe-cd#153]
**Describe the bug**
argo-cd is not syncing from VCS due to credential issues
![argocd-issue](https://user-images.githubusercontent.com/14028058/96020603-e7e89100-0e6b-11eb-83e5-7363a1d8dff9.png)

**To Reproduce**
1. Go to 'https://argocd-server-aicoe-argocd.apps.ocp4.prod.psi.redhat.com/'
2. Click on any application in thoth-station.
3. Scroll down to 'errors'

**Expected behavior**
sync effectively based  on changes in vcs.

**Comment by harshad16** [comment]
With the update in #152 , the project running `cluster: ocp4.prod.psi.redhat.com` was fixed.
However project in `cluster: ocp.prod.psi.redhat.com` is still giving out the same issue.
with further checking, I feel it could be the issue of the role, the argocd-manager-role is present in all projects in ocp cluster.
however, it feels the namespace, **aicoe-argocd** which had the service-account `argocd-manager` is no longer present in the cluster. or maybe we have lost the access, so couldn't check further, will try to reach out to aicoe-sre people.

**Comment by harshad16** [comment]
as the pr #152  , was generated without updating the encryption on the files, it causing issues in `ocp.prod.psi.redhat.com` cluster only, however the manually change of removing the files have fixed the issue for `ocp4.prod.psi.redhat.com` applications and they are able to sync. 
I m not entirely sure if the above-stated issue would be fixed by fixing the encryption but the encryption of the file is definitely needed to be changed.

**Comment by anishasthana** [comment]
Has this been resolved? I know one of the issues we had was that a namespace was deleted (we've recreated it)

**Comment by HumairAK** [comment]
Yes it's resolved, closing.
