### ISSUE TITLE
A cluster spec for each project for each cluster

### ISSUE THREAD

**Issue by HumairAK** [AICoE/aicoe-cd#169]
Currently for each cluster we have 1 corresponding cluster secret in the argocd namespace. For each cluster secret, we have a list of namespaces that argocd should have access to.  For example for the ocp4 cluster argocd can manage these namespaces [here](https://github.com/AICoE/aicoe-cd/blob/master/manifests/overlays/prod/secrets/clusters/api.ocp4.prod.psi.redhat.com.enc.yaml#L13). 

But if you notice, we group namespaces for all argocd projects in there. So you have thoth/idh/aiops namespaces for ocp4 listed in the same cluster spec. 

The problem with this is, suppose thoth team deletes a namespace from their cluster (and thus the argocd-manager-rolebinding in that namespace), then argocd will start reporting errors (because of how its discovery works) for every team's application using that cluster spec. 

Why not use multiple cluster specs per project? 
Because argocd cannot have more than 1 cluster spec per cluster, because it uses the cluster url to read the spec and requires it to be unique. Luckily there's a workaround listed [here](https://github.com/argoproj/argo-cd/issues/2288). I think we should use this to create a separate cluster spec for each team/project, and if, for example, idh team needs to onboard a new namespace, they will go edit the idh cluster spec for ocp 4.

**Comment by accorvin** [comment]
+1 I like this proposal.

**Comment by anishasthana** [comment]
With the change we have to support multiple gpg keys, we will also be able to get around having a data hub admin review all changes for cluster specs. The thoth team can review and update their own cluster spec as desired.
