### ISSUE TITLE
Docs for ksops

### ISSUE THREAD

**Issue by tumido** [AICoE/aicoe-cd#28]
**Is your feature request related to a problem? Please describe.**
Better docs coverage on `ksops` - a how to, step by step guide for new apps being onboarded.

**Describe the solution you'd like**
I want @HumairAK to go and write down all the things we chatted about and make it a nice How to guide. :stuck_out_tongue: 

**Describe alternatives you've considered**
 n/a

**Additional context**
 n/a

**Comment by tumido** [comment]
pretty please!

**Comment by accorvin** [comment]
@tumido I've created https://issues.redhat.com/browse/AICOESRE-95 to track this work. We'll discuss prioritization of this at our next sprint planning meeting

**Comment by HumairAK** [comment]
Fixed by https://github.com/AICoE/aicoe-cd/pull/44
