### ISSUE TITLE
Deploy and Maintain a 'CI/CD Pipeline Keylime' Demo

### ISSUE THREAD

**Issue by goern** [AICoE/aicoe-cd#308]
As an Application Owner,
I want to continuously deploy my application by an OpenShift Pipeline,
so that its execution is governed by Keylime

**Acceptance Criteria**
- [ ] decide which application to be used for the demo, in the best case some AI related
- [ ] document prerequisites for keylime deployment on op1st
- [ ] criteria that prevent the application from being run are documents
- [ ] describe the 'hack the worker node' activity
- [ ] create op1st ADR on how to deploy Keylime
- [ ] an application is built via Tekton Pipeline and delivered as a container image
- [ ] the application's container image is deployed via a Tekton Pipeline to an Operate First namespace
- [ ] a demo is created

**References**
* https://github.com/keylime/keylime
* https://github.com/redhat-et/edge-security-demo

**Comment by goern** [comment]
@axelsimon

**Comment by goern** [comment]
/remove-lifecycle stale
/lifecycle frozen

@harshad16 what is the current status of this?

**Comment by harshad16** [comment]
I think @codificat  was trying the keylime . It needed some instruction set available or hardware type node to available.
Or maybe i m confused with some other project. 
@codificat  can you please correct if i m wrong.

**Comment by codificat** [comment]
That's correct: the keylime agent running on the nodes relies on a (hardware) TPM. For demo purposes, this could be emulated in software.

The agent also is not very container-friendly at the moment. On one hand, it would target more at the integrity of the nodes themselves than to specific apps.

But beyond that: the current implementation of the agent is hard to manage in a containerized environment. There is work in progress for a rewrite in Rust that would improve that.

I have not checked the status of this for a while, I will find out an update with more details.
