### ISSUE TITLE
stage-thoth-prescriptions-refresh-job app is not available in argocd and manifests are missing

### ISSUE THREAD

**Issue by pacospace** [AICoE/aicoe-cd#746]
**Describe the bug**
stage-thoth-prescriptions-refresh-job app is not available in argocd and manifests are missing https://console-openshift-console.apps.ocp4.prod.psi.redhat.com/api-resource/ns/aicoe-argocd/argoproj.io~v1alpha1~CronWorkflow/instances

**To Reproduce**
1. Go to thoth-middletier-stage and check for argo cronworkflow

**Expected behavior**
app is not available in argocd and manifests are missing

**Screenshots**

**Additional context**
https://argocd-server-aicoe-argocd.apps.ocp4.prod.psi.redhat.com/applications?proj=&sync=&health=&namespace=thoth-middletier-stage&cluster=&labels=

PR that added the app: https://github.com/AICoE/aicoe-cd/pull/744

**Comment by anishasthana** [comment]
@harshad16 do we still care about this? If not, can the issue be closed?

**Comment by harshad16** [comment]
This is completed
thanks everyone. :+1:
